apiVersion: v1
kind: Secret
metadata:
  name: carto-smartagg-secrets
type: Opaque
data:
  # To "encrypt" a variable use the command: `printf "my_value" | base64`
  # To "encrypt" a file use the command `base64 -w 0 my_file.yml`
  task-config.yaml: "ZHVtbXk="
